[tool.poetry]
name = "rag"
version = "0.1.0"
description = "RAG Architecture examples"
authors = ["Jose Alcocer <jolual2747@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
pandas = "1.5"
transformers = "4.32.1"
chromadb = "0.3.29"
ipykernel = "^6.29.4"
openai = "^1.14.3"
gensim = "^4.3.2"
nltk = "^3.8.1"
langchain = "^0.1.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
